# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'IJKMediaDemo' do

pod 'MD360Player4iOS', '~> 1.1.1.beta'

end

